import { useState } from "react";
import { computeDailyBudget, todayIso } from "../domain/daily-budget";
import type { BudgetCategory, RecurringBill, Transaction } from "../domain/types";
import { Button, EmptyState, formatCurrency, formatDate, PageIntro } from "./Common";
import { DailyBudgetCard } from "./DailyBudgetCard";
import { Icon } from "./Icon";

export function FinanceView({ transactions, bills, budgetCategories, onAddTransaction, onUpdateTransaction, onDeleteTransaction, onToggleBill, onAddBill, onUpdateBill, onDeleteBill, onAddBudgetCategory, onUpdateBudgetCategory, onDeleteBudgetCategory }: { transactions: Transaction[]; bills: RecurringBill[]; budgetCategories: BudgetCategory[]; onAddTransaction: (item: Transaction) => void; onUpdateTransaction: (item: Transaction) => void; onDeleteTransaction: (id: string) => void; onToggleBill: (id: string) => void; onAddBill: (item: RecurringBill) => void; onUpdateBill: (item: RecurringBill) => void; onDeleteBill: (id: string) => void; onAddBudgetCategory: (item: BudgetCategory) => void; onUpdateBudgetCategory: (item: BudgetCategory) => void; onDeleteBudgetCategory: (id: string) => void }) {
  const [transactionForm, setTransactionForm] = useState<Transaction | null | undefined>(undefined); const [billForm, setBillForm] = useState<RecurringBill | null | undefined>(undefined); const [categoryForm, setCategoryForm] = useState<BudgetCategory | null | undefined>(undefined);
  const income = transactions.filter((item) => item.type === "income").reduce((sum, item) => sum + item.amount, 0); const transactionExpenses = transactions.filter((item) => item.type === "expense").reduce((sum, item) => sum + item.amount, 0); const paidBills = bills.filter((bill) => bill.paid).reduce((sum, bill) => sum + bill.amount, 0); const expenses = transactionExpenses + paidBills;
  const dailyBudget = computeDailyBudget({ today: todayIso(), transactions, bills, categories: budgetCategories });
  return <>
    <PageIntro eyebrow="Visão simples" title="Finanças" description="Registre o que entra e sai. O controle começa com dados claros." action={<Button onClick={() => setTransactionForm(null)}><Icon name="plus" /> Registrar movimento</Button>} />
    <DailyBudgetCard result={dailyBudget} />
    <section className="finance-summary"><div className="card"><span>Saldo calculado</span><strong>{formatCurrency(income - expenses)}</strong><small>Com base nos lançamentos salvos</small></div><div className="card"><span>Receitas</span><strong className="positive">{formatCurrency(income)}</strong><small>Entradas registradas</small></div><div className="card"><span>Despesas</span><strong className="negative">{formatCurrency(expenses)}</strong><small>Saídas registradas</small></div></section>
    {transactionForm !== undefined && <TransactionForm initial={transactionForm ?? undefined} onSave={(item) => { transactionForm ? onUpdateTransaction(item) : onAddTransaction(item); setTransactionForm(undefined); }} onCancel={() => setTransactionForm(undefined)} />}
    {billForm !== undefined && <BillForm initial={billForm ?? undefined} onSave={(item) => { billForm ? onUpdateBill(item) : onAddBill(item); setBillForm(undefined); }} onCancel={() => setBillForm(undefined)} />}
    {categoryForm !== undefined && <BudgetCategoryForm initial={categoryForm ?? undefined} onSave={(item) => { categoryForm ? onUpdateBudgetCategory(item) : onAddBudgetCategory(item); setCategoryForm(undefined); }} onCancel={() => setCategoryForm(undefined)} />}
    <section className="lower-grid finance-lower"><article className="card list-card"><div className="card-heading"><h2>Lançamentos recentes</h2></div>{transactions.length ? transactions.slice().reverse().map((item) => <TransactionRow key={item.id} item={item} onEdit={() => setTransactionForm(item)} onDelete={() => { if (window.confirm("Excluir este lançamento?")) onDeleteTransaction(item.id); }} />) : <EmptyState title="Nenhum lançamento" description="Registre sua primeira receita ou despesa." />}</article><article className="card list-card"><div className="card-heading"><h2>Contas recorrentes</h2><button className="link-button" onClick={() => setBillForm(null)}><Icon name="plus" /> Nova conta</button></div>{bills.length ? bills.map((bill) => <BillRow key={bill.id} bill={bill} onToggle={() => onToggleBill(bill.id)} onEdit={() => setBillForm(bill)} onDelete={() => { if (window.confirm("Excluir esta conta recorrente?")) onDeleteBill(bill.id); }} />) : <EmptyState title="Nenhuma conta" description="Cadastre uma conta recorrente para acompanhar vencimentos." />}</article></section>
    <article className="card list-card budget-categories-card"><div className="card-heading"><h2>Categorias de gasto diário</h2><button className="link-button" onClick={() => setCategoryForm(null)}><Icon name="plus" /> Nova categoria</button></div><p className="muted small-print">Gastos do dia a dia que normalmente não viram lançamento (transporte, lazer, futilidades). O valor mensal alimenta o cálculo do controle diário acima.</p>{budgetCategories.length ? budgetCategories.map((category) => <BudgetCategoryRow key={category.id} category={category} onEdit={() => setCategoryForm(category)} onDelete={() => { if (window.confirm(`Excluir a categoria "${category.name}"?`)) onDeleteBudgetCategory(category.id); }} />) : <EmptyState title="Nenhuma categoria" description="Cadastre uma estimativa mensal para entrar no cálculo do controle diário." />}</article>
  </>;
}

function TransactionForm({ initial, onSave, onCancel }: { initial?: Transaction; onSave: (item: Transaction) => void; onCancel: () => void }) { const [type, setType] = useState<Transaction["type"]>(initial?.type ?? "expense"); const [description, setDescription] = useState(initial?.description ?? ""); const [amount, setAmount] = useState(initial?.amount?.toString().replace(".", ",") ?? ""); function submit(event: React.FormEvent) { event.preventDefault(); const parsed = Number(amount.replace(",", ".")); if (!description.trim() || !parsed) return; onSave({ id: initial?.id ?? `transaction-${Date.now()}`, type, description: description.trim(), amount: parsed, date: initial?.date ?? "2026-08-14", category: initial?.category ?? "Geral", account: initial?.account ?? "Conta principal" }); } return <form className="card form-card" onSubmit={submit}><div className="form-heading"><h2>{initial ? "Editar lançamento" : "Novo movimento"}</h2><button type="button" className="icon-close" onClick={onCancel} aria-label="Fechar"><Icon name="close" /></button></div><div className="segmented"><button type="button" className={type === "expense" ? "selected" : ""} onClick={() => setType("expense")}>Despesa</button><button type="button" className={type === "income" ? "selected" : ""} onClick={() => setType("income")}>Receita</button></div><label>Descrição<input autoFocus value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Valor<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><div className="form-actions"><Button variant="secondary" onClick={onCancel}>Cancelar</Button><Button type="submit">{initial ? "Salvar alterações" : "Salvar movimento"}</Button></div></form>; }
function BillForm({ initial, onSave, onCancel }: { initial?: RecurringBill; onSave: (item: RecurringBill) => void; onCancel: () => void }) { const [name, setName] = useState(initial?.name ?? ""); const [amount, setAmount] = useState(initial?.amount?.toString().replace(".", ",") ?? ""); const [dueDate, setDueDate] = useState(initial?.dueDate ?? "2026-08-15"); function submit(event: React.FormEvent) { event.preventDefault(); const parsed = Number(amount.replace(",", ".")); if (!name.trim() || !parsed) return; onSave({ id: initial?.id ?? `bill-${Date.now()}`, name: name.trim(), amount: parsed, dueDate, paid: initial?.paid ?? false }); } return <form className="card form-card" onSubmit={submit}><div className="form-heading"><h2>{initial ? "Editar conta" : "Nova conta recorrente"}</h2><button type="button" className="icon-close" onClick={onCancel} aria-label="Fechar"><Icon name="close" /></button></div><label>Nome<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: aluguel" /></label><div className="form-grid"><label>Valor<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0,00" /></label><label>Vencimento<input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} /></label></div><div className="form-actions"><Button variant="secondary" onClick={onCancel}>Cancelar</Button><Button type="submit">{initial ? "Salvar alterações" : "Salvar conta"}</Button></div></form>; }
function TransactionRow({ item, onEdit, onDelete }: { item: Transaction; onEdit: () => void; onDelete: () => void }) { return <div className="transaction-row"><span className={`transaction-icon ${item.type}`}>{item.type === "income" ? "↑" : "↓"}</span><div><strong>{item.description}</strong><small>{formatDate(item.date)} · {item.category}</small></div><strong className={item.type === "income" ? "positive" : "negative"}>{item.type === "income" ? "+" : "−"}{formatCurrency(item.amount)}</strong><button className="edit-button" onClick={onEdit}>Editar</button><button className="delete-button" onClick={onDelete} aria-label={`Excluir ${item.description}`}><Icon name="close" /></button></div>; }
function BillRow({ bill, onToggle, onEdit, onDelete }: { bill: RecurringBill; onToggle: () => void; onEdit: () => void; onDelete: () => void }) { return <div className="bill-row"><button className={`check-button ${bill.paid ? "checked" : ""}`} onClick={onToggle} aria-label="Marcar conta como paga">{bill.paid && <Icon name="check" />}</button><div><strong className={bill.paid ? "paid-text" : ""}>{bill.name}</strong><small>vence em {formatDate(bill.dueDate)}</small></div><strong>{formatCurrency(bill.amount)}</strong><button className="edit-button" onClick={onEdit}>Editar</button><button className="delete-button" onClick={onDelete} aria-label={`Excluir ${bill.name}`}><Icon name="close" /></button></div>; }
function BudgetCategoryForm({ initial, onSave, onCancel }: { initial?: BudgetCategory; onSave: (item: BudgetCategory) => void; onCancel: () => void }) { const [name, setName] = useState(initial?.name ?? ""); const [monthlyAmount, setMonthlyAmount] = useState(initial?.monthlyAmount?.toString().replace(".", ",") ?? ""); function submit(event: React.FormEvent) { event.preventDefault(); const parsed = Number(monthlyAmount.replace(",", ".")); if (!name.trim() || !parsed) return; onSave({ id: initial?.id ?? `budget-category-${Date.now()}`, name: name.trim(), monthlyAmount: parsed }); } return <form className="card form-card" onSubmit={submit}><div className="form-heading"><h2>{initial ? "Editar categoria" : "Nova categoria de gasto diário"}</h2><button type="button" className="icon-close" onClick={onCancel} aria-label="Fechar"><Icon name="close" /></button></div><label>Nome<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: transporte" /></label><label>Valor estimado por mês<input inputMode="decimal" value={monthlyAmount} onChange={(event) => setMonthlyAmount(event.target.value)} placeholder="0,00" /></label><div className="form-actions"><Button variant="secondary" onClick={onCancel}>Cancelar</Button><Button type="submit">{initial ? "Salvar alterações" : "Salvar categoria"}</Button></div></form>; }
function BudgetCategoryRow({ category, onEdit, onDelete }: { category: BudgetCategory; onEdit: () => void; onDelete: () => void }) { return <div className="bill-row"><div><strong>{category.name}</strong><small>{formatCurrency(category.monthlyAmount / 30)}/dia (aprox.)</small></div><strong>{formatCurrency(category.monthlyAmount)}/mês</strong><button className="edit-button" onClick={onEdit}>Editar</button><button className="delete-button" onClick={onDelete} aria-label={`Excluir ${category.name}`}><Icon name="close" /></button></div>; }
