import { useMemo, useState } from "react";
import type { AppData, Task, Transaction, RecurringBill } from "../domain/types";
import { Button, EmptyState, formatCurrency, formatDate } from "./Common";
import { Icon } from "./Icon";

type Row = { id: string; date: string; type: "Tarefa" | "Receita" | "Despesa" | "Conta"; description: string; status: string; amount?: number; detail: string; source: "task" | "transaction" | "bill" };

export function SpreadsheetView({ data, onToggleTask, onToggleBill, onDelete }: { data: AppData; onToggleTask: (id: string) => void; onToggleBill: (id: string) => void; onDelete: (row: Row) => void }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("todos");
  const [selected, setSelected] = useState<Row | null>(null);
  const rows = useMemo<Row[]>(() => [
    ...data.tasks.map((item: Task) => ({ id: item.id, date: item.date, type: "Tarefa" as const, description: item.title, status: item.status === "completed" ? "Concluída" : "Em aberto", detail: `${item.priority}${item.time ? ` · ${item.time}` : ""}`, source: "task" as const })),
    ...data.transactions.map((item: Transaction) => ({ id: item.id, date: item.date, type: item.type === "income" ? "Receita" as const : "Despesa" as const, description: item.description, status: "Registrado", amount: item.amount, detail: `${item.category} · ${item.account}`, source: "transaction" as const })),
    ...data.bills.map((item: RecurringBill) => ({ id: item.id, date: item.dueDate, type: "Conta" as const, description: item.name, status: item.paid ? "Paga" : "Pendente", amount: item.amount, detail: "Recorrente", source: "bill" as const })),
  ].sort((a, b) => b.date.localeCompare(a.date)), [data]);
  const visible = rows.filter((row) => (filter === "todos" || row.source === filter || row.status.toLowerCase().includes(filter)) && `${row.description} ${row.detail} ${row.type}`.toLowerCase().includes(query.toLowerCase()));
  const income = data.transactions.filter((item) => item.type === "income").reduce((sum, item) => sum + item.amount, 0);
  const expenses = data.transactions.filter((item) => item.type === "expense").reduce((sum, item) => sum + item.amount, 0) + data.bills.filter((item) => item.paid).reduce((sum, item) => sum + item.amount, 0);
  const pending = data.tasks.filter((item) => item.status === "pending").length + data.bills.filter((item) => !item.paid).length;

  return <section className="spreadsheet-view">
    <div className="spreadsheet-heading"><div><p className="eyebrow">Visão geral</p><h1>Planilha</h1><p className="intro-copy">Todos os seus registros em uma única mesa de trabalho.</p></div><Button onClick={() => document.querySelector<HTMLInputElement>(".spreadsheet-search")?.focus()}><Icon name="plus" /> Registro rápido</Button></div>
    <div className="spreadsheet-summary"><Summary label="Saldo" value={formatCurrency(income - expenses)} tone="accent" /><Summary label="Receitas" value={formatCurrency(income)} tone="positive" /><Summary label="Despesas" value={formatCurrency(expenses)} tone="negative" /><Summary label="Pendências" value={String(pending)} tone="warning" /></div>
    <div className="spreadsheet-toolbar"><input className="spreadsheet-search" aria-label="Buscar na planilha" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar na planilha..." /><select aria-label="Filtrar registros" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="todos">Todos os registros</option><option value="task">Tarefas</option><option value="transaction">Lançamentos</option><option value="bill">Contas</option><option value="pendente">Pendentes</option><option value="completed">Concluídas</option></select><span className="spreadsheet-count">{visible.length} registros</span></div>
    <div className="spreadsheet-layout"><div className="spreadsheet-table-wrap"><table className="spreadsheet-table"><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Status</th><th>Detalhes</th><th className="amount-cell">Valor</th><th /></tr></thead><tbody>{visible.map((row) => <tr key={`${row.source}-${row.id}`} className={selected?.id === row.id ? "selected" : ""} onClick={() => setSelected(row)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(row); } }} tabIndex={0} role="button" aria-label={`Ver detalhes de ${row.description}`}><td>{formatDate(row.date)}</td><td><span className={`sheet-type ${row.source}`}>{row.type}</span></td><td><strong>{row.description}</strong></td><td><span className={`sheet-status ${statusClass(row.status)}`}>{row.status}</span></td><td className="muted">{row.detail}</td><td className={`amount-cell ${row.type === "Receita" ? "positive" : row.type === "Despesa" || row.type === "Conta" ? "negative" : ""}`}>{row.amount === undefined ? "—" : formatCurrency(row.amount)}</td><td><button className="sheet-action" onClick={(event) => { event.stopPropagation(); row.source === "task" ? onToggleTask(row.id) : row.source === "bill" ? onToggleBill(row.id) : setSelected(row); }}>{row.source === "task" ? row.status === "Concluída" ? "Reabrir" : "Concluir" : row.source === "bill" ? row.status === "Paga" ? "Reabrir" : "Pagar" : "Abrir"}</button></td></tr>)}</tbody></table>{!visible.length && <EmptyState title="Nenhum registro encontrado" description="Ajuste os filtros ou registre um novo item." />}</div><aside className="sheet-detail card">{selected ? <><p className="eyebrow">Registro selecionado</p><h2>{selected.description}</h2><p className="muted">{selected.type} · {formatDate(selected.date)}</p><div className="detail-line"><span>Status</span><strong>{selected.status}</strong></div><div className="detail-line"><span>Detalhes</span><strong>{selected.detail}</strong></div>{selected.amount !== undefined && <div className="detail-line"><span>Valor</span><strong>{formatCurrency(selected.amount)}</strong></div>}<button className="delete-button sheet-delete" onClick={() => onDelete(selected)}>Excluir registro</button></> : <><p className="eyebrow">Detalhes</p><h2>Selecione uma linha</h2><p className="muted">Escolha um registro para visualizar ações e informações completas.</p></>}</aside></div>
  </section>;
}

function Summary({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="sheet-summary-card"><span>{label}</span><strong className={tone}>{value}</strong></div>; }
function statusClass(status: string) { return status === "Concluída" || status === "Paga" ? "done" : status === "Pendente" || status === "Em aberto" ? "pending" : "neutral"; }
